language: ruby
install:
  - sudo apt-get update -qq
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq build-essential patch ruby-dev zlib1g-dev liblzma-dev firebird-dev firebird2.5-superclassic
  - bundle
before_script:  
  - sudo gsec -modify SYSDBA -pw masterkey  
  - sudo mkdir -p /tmp/firebird
  - sudo chown firebird.firebird /tmp/firebird
  - sudo chmod 0777 /tmp/firebird
script:
  - bundle exec rake compile:fb_ext test
rvm:  
  - 2.5
  - 2.6
  - 2.7
